import { Link } from 'react-router-dom';
import { BookOpen, BrainCircuit, Bot } from 'lucide-react'; // Icons for our features

const HomePage = () => {
  return (
    <div className="bg-background text-foreground">
      {/* --- HERO SECTION --- */}
      {/* This is the main "above the fold" content that grabs the user's attention. */}
      <section className="container mx-auto px-4 py-20 text-center flex flex-col items-center">
        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight">
          The Smart Way to Master Japanese <span className="text-primary">Reading</span>.
        </h1>
        <p className="mt-6 max-w-2xl text-lg md:text-xl text-muted-foreground">
          YomiRen turns any Japanese text into an interactive learning lesson. Analyze articles, stories, and more to build your vocabulary and accelerate your journey to fluency.
        </p>
        <Link 
          to="/register"
          className="mt-8 bg-primary text-primary-foreground font-bold text-lg py-3 px-8 rounded-lg hover:opacity-90 transition-transform hover:scale-105"
        >
          Get Started for Free
        </Link>
      </section>

      {/* --- FEATURES SECTION --- */}
      {/* This section showcases the three core tools of our application. */}
      <section className="bg-card/50 py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Everything You Need to Read with Confidence</h2>
          {/* A responsive grid that's 1 column on mobile and 3 on desktop. */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
            {/* Feature 1: Analyzer */}
            <div className="flex flex-col items-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <BookOpen size={32} className="text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Interactive Text Analysis</h3>
              <p className="text-muted-foreground">
                Paste any text and instantly see definitions for unknown words with a single click.
              </p>
            </div>
            {/* Feature 2: SRS */}
            <div className="flex flex-col items-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <BrainCircuit size={32} className="text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Smart Flashcard Reviews</h3>
              <p className="text-muted-foreground">
                Never forget a word with our built-in Spaced Repetition System (SRS).
              </p>
            </div>
            {/* Feature 3: AI */}
            <div className="flex flex-col items-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <Bot size={32} className="text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">AI-Powered Sentences</h3>
              <p className="text-muted-foreground">
                Deepen your understanding with unique example sentences generated by AI.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* --- FINAL CTA SECTION --- */}
      <section className="container mx-auto px-4 py-20 text-center">
        <h2 className="text-3xl font-bold">Ready to Start Your Journey?</h2>
        <Link 
          to="/register"
          className="mt-8 inline-block bg-primary text-primary-foreground font-bold text-lg py-3 px-8 rounded-lg hover:opacity-90 transition-transform hover:scale-105"
        >
          Create Your Free Account
        </Link>
      </section>
    </div>
  );
};

export default HomePage;